In [82]:
# import libraries

import pandas as pd
import datetime as datetime

In [83]:
# Load files to be merged

weather_to_load = "Resources/weather_frialsa.csv"
alarms_to_load = "Resources/saveris_alarms_complete.csv"

weather_frialsa_df = pd.read_csv(weather_to_load)
alarms_df = pd.read_csv(alarms_to_load)

alarms_df.head()

,date,location,status,alarm_type,limit,value,platform_1,platform_2,deepfreezer_1,deepfreezer_2,freezer_1,freezer_2,freezer_3,freezer_4,cooling_1,cooling_2,sensor_alarm
0,24/06/21 16:45,Freezer,0,recovery,-19,-19.3,3.7,1.4,-20.0,-22.9,-19.3,-19.1,-18.1,-20.8,3.9,3.9,freezer_1
1,24/06/21 16:45,Freezer,0,recovery,-19,-19.1,3.7,1.4,-20.0,-22.9,-19.3,-19.1,-18.1,-20.8,3.9,3.9,freezer_2
2,24/06/21 17:00,Freezer,0,recovery,-19,-20.0,2.3,0.1,-23.0,-24.0,-20.2,-19.9,-20.0,-21.6,3.4,3.5,freezer_3
3,24/06/21 17:30,Deepfreezer,0,recovery,-25,-25.9,2.4,0.6,-25.9,-25.0,-20.9,-20.8,-21.2,-22.1,3.1,3.2,deepfreezer_1
4,24/06/21 17:30,Deepfreezer,0,recovery,-25,-25.0,2.4,0.6,-25.9,-25.0,-20.9,-20.8,-21.2,-22.1,3.1,3.2,deepfreezer_2

In [84]:

# cpnvert the dt Time Format to Timestamp('2017-03-22 15:16:45')
pd.to_datetime(1622505600, unit='s')

weather_frialsa_df['dt'] = pd.to_datetime(weather_frialsa_df['dt'], unit='s')
weather_frialsa_df.head()

# alarms_df['date'] =  pd.to_datetime(alarms_df['date'], format='%d/%m/%y %H:%M')
# alarms_df.dtypes

,dt,dt_iso,timezone,city_name,lat,lon,temp,visibility,dew_point,feels_like,...,wind_gust,rain_1h,rain_3h,snow_1h,snow_3h,clouds_all,weather_id,weather_main,weather_description,weather_icon
0,2021-06-24 16:00:00,2021-06-24 16:00:00 +0000 UTC,-18000,Frialsa,19.638615,-99.145726,18.85,NaN,14.53,18.78,...,NaN,NaN,NaN,NaN,NaN,65,803,Clouds,broken clouds,04d
1,2021-06-24 17:00:00,2021-06-24 17:00:00 +0000 UTC,-18000,Frialsa,19.638615,-99.145726,19.68,NaN,12.20,19.32,...,NaN,NaN,NaN,NaN,NaN,63,803,Clouds,broken clouds,04d
2,2021-06-24 18:00:00,2021-06-24 18:00:00 +0000 UTC,-18000,Frialsa,19.638615,-99.145726,21.11,NaN,12.53,20.79,...,NaN,0.16,NaN,NaN,NaN,43,500,Rain,light rain,10d
3,2021-06-24 19:00:00,2021-06-24 19:00:00 +0000 UTC,-18000,Frialsa,19.638615,-99.145726,21.86,NaN,12.97,21.59,...,NaN,0.16,NaN,NaN,NaN,57,500,Rain,light rain,10d
4,2021-06-24 20:00:00,2021-06-24 20:00:00 +0000 UTC,-18000,Frialsa,19.638615,-99.145726,22.18,NaN,13.53,21.97,...,NaN,NaN,NaN,NaN,NaN,64,803,Clouds,broken clouds,04d

In [85]:
# Convert the new date object to datetime64
weather_frialsa_df['dt'] = pd.to_datetime(weather_frialsa_df['dt'], format='%d/%m/%y %H:%M')
weather_frialsa_df.dtypes

dt                     datetime64[ns]
dt_iso                         object
timezone                        int64
city_name                      object
lat                           float64
lon                           float64
temp                          float64
visibility                    float64
dew_point                     float64
feels_like                    float64
temp_min                      float64
temp_max                      float64
pressure                        int64
sea_level                     float64
grnd_level                    float64
humidity                        int64
wind_speed                    float64
wind_deg                        int64
wind_gust                     float64
rain_1h                       float64
rain_3h                       float64
snow_1h                       float64
snow_3h                       float64
clouds_all                      int64
weather_id                      int64
weather_main                   object
weather_description            object
weather_icon                   object
dtype: object

In [86]:
# Rename columns to date so we can merge on 'date' column

weather_frialsa_df = weather_frialsa_df.rename(columns={'dt':'date'})
weather_frialsa_df.head()

,date,dt_iso,timezone,city_name,lat,lon,temp,visibility,dew_point,feels_like,...,wind_gust,rain_1h,rain_3h,snow_1h,snow_3h,clouds_all,weather_id,weather_main,weather_description,weather_icon
0,2021-06-24 16:00:00,2021-06-24 16:00:00 +0000 UTC,-18000,Frialsa,19.638615,-99.145726,18.85,NaN,14.53,18.78,...,NaN,NaN,NaN,NaN,NaN,65,803,Clouds,broken clouds,04d
1,2021-06-24 17:00:00,2021-06-24 17:00:00 +0000 UTC,-18000,Frialsa,19.638615,-99.145726,19.68,NaN,12.20,19.32,...,NaN,NaN,NaN,NaN,NaN,63,803,Clouds,broken clouds,04d
2,2021-06-24 18:00:00,2021-06-24 18:00:00 +0000 UTC,-18000,Frialsa,19.638615,-99.145726,21.11,NaN,12.53,20.79,...,NaN,0.16,NaN,NaN,NaN,43,500,Rain,light rain,10d
3,2021-06-24 19:00:00,2021-06-24 19:00:00 +0000 UTC,-18000,Frialsa,19.638615,-99.145726,21.86,NaN,12.97,21.59,...,NaN,0.16,NaN,NaN,NaN,57,500,Rain,light rain,10d
4,2021-06-24 20:00:00,2021-06-24 20:00:00 +0000 UTC,-18000,Frialsa,19.638615,-99.145726,22.18,NaN,13.53,21.97,...,NaN,NaN,NaN,NaN,NaN,64,803,Clouds,broken clouds,04d

In [87]:
# Change data type of date in alarms_df to be sure to merge through 'date' with datetime64
alarms_df['date'] =  pd.to_datetime(alarms_df['date'], format='%d/%m/%y %H:%M')
alarms_df.dtypes

date             datetime64[ns]
location                 object
status                    int64
alarm_type               object
limit                     int64
value                   float64
platform_1              float64
platform_2              float64
deepfreezer_1           float64
deepfreezer_2           float64
freezer_1               float64
freezer_2               float64
freezer_3               float64
freezer_4               float64
cooling_1               float64
cooling_2               float64
sensor_alarm             object
dtype: object

In [88]:
# Double check shape of pd dfs to be merged

print(f"Alarms df: {alarms_df.shape}")
print(f"Weather df: {weather_frialsa_df.shape}")

Alarms df: (7123, 17)
Weather df: (7472, 28)

In [89]:
# Merge both on date time

df_weather_alarms = pd.merge(alarms_df, weather_frialsa_df, on='date', how='left')
print(df_weather_alarms.shape)
df_weather_alarms[6650:6700]

(7123, 44)

,date,location,status,alarm_type,limit,value,platform_1,platform_2,deepfreezer_1,deepfreezer_2,...,wind_gust,rain_1h,rain_3h,snow_1h,snow_3h,clouds_all,weather_id,weather_main,weather_description,weather_icon
6650,2022-04-30 18:45:00,Freezer,1,deficit,-24,-24.3,2.4,1.6,-30.8,-30.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6651,2022-04-30 19:00:00,Freezer,0,recovery,-24,-23.9,2.9,2.6,-29.7,-29.6,...,NaN,NaN,NaN,NaN,NaN,99.0,804.0,Clouds,overcast clouds,04d
6652,2022-04-30 19:15:00,Freezer,1,deficit,-24,-24.6,1.8,1.0,-30.1,-29.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6653,2022-04-30 21:45:00,Freezer,1,deficit,-24,-24.5,1.3,0.7,-29.8,-29.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6654,2022-04-30 23:00:00,Freezer,0,recovery,-24,-23.8,1.8,0.9,-29.5,-29.4,...,NaN,NaN,NaN,NaN,NaN,89.0,804.0,Clouds,overcast clouds,04d
6655,2022-04-30 23:00:00,Freezer,0,recovery,-24,-23.8,1.8,0.9,-29.5,-29.4,...,NaN,NaN,NaN,NaN,NaN,89.0,804.0,Clouds,overcast clouds,04d
6656,2022-04-30 23:45:00,Freezer,1,deficit,-24,-25.0,1.8,1.0,-29.2,-28.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6657,2022-05-01 00:15:00,Freezer,1,deficit,-24,-25.0,1.9,0.9,-30.1,-29.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6658,2022-05-01 03:00:00,Freezer,0,recovery,-24,-23.9,2.1,1.0,-30.9,-30.7,...,NaN,NaN,NaN,NaN,NaN,44.0,802.0,Clouds,scattered clouds,03n
6659,2022-05-01 03:30:00,Freezer,0,recovery,-24,-23.8,2.1,0.6,-30.8,-30.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6660,2022-05-01 04:15:00,Freezer,0,recovery,-24,-23.9,2.1,1.3,-30.3,-30.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6661,2022-05-01 04:45:00,Freezer,1,deficit,-24,-24.6,1.5,0.4,-29.4,-29.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6662,2022-05-01 05:15:00,Freezer,1,deficit,-24,-24.5,1.2,0.4,-28.5,-28.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6663,2022-05-01 07:30:00,Freezer,1,deficit,-24,-24.1,1.8,1.1,-26.7,-26.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6664,2022-05-01 13:15:00,Freezer,0,recovery,-24,-23.8,3.1,2.3,-30.4,-30.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6665,2022-05-01 13:15:00,Freezer,0,recovery,-24,-23.8,3.1,2.3,-30.4,-30.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6666,2022-05-01 13:30:00,Freezer,0,recovery,-24,-23.8,2.8,2.0,-30.4,-30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6667,2022-05-01 15:15:00,Freezer,1,deficit,-24,-24.4,3.0,2.9,-31.3,-31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6668,2022-05-01 15:45:00,Freezer,1,deficit,-24,-24.8,2.9,2.3,-31.6,-31.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6669,2022-05-01 16:00:00,Freezer,1,deficit,-24,-24.5,2.8,2.5,-31.8,-31.4,...,NaN,NaN,NaN,NaN,NaN,88.0,804.0,Clouds,overcast clouds,04d
6670,2022-05-01 21:30:00,Freezer,0,recovery,-24,-23.9,2.4,1.2,-30.0,-29.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6671,2022-05-01 23:30:00,Freezer,0,recovery,-24,-23.9,2.7,1.9,-31.7,-31.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6672,2022-05-01 23:45:00,Freezer,0,recovery,-24,-23.9,2.5,1.1,-31.8,-31.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6673,2022-05-01 23:45:00,Freezer,1,deficit,-24,-24.5,2.5,1.1,-31.8,-31.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6674,2022-05-02 01:45:00,Deepfreezer,0,recovery,-32,-32.1,1.5,0.8,-32.1,-31.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6675,2022-05-02 02:00:00,Freezer,1,deficit,-24,-24.7,2.1,1.3,-32.2,-31.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6676,2022-05-02 02:15:00,Deepfreezer,0,recovery,-32,-32.1,2.1,1.1,-32.3,-32.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6677,2022-05-02 02:30:00,Freezer,1,deficit,-24,-25.2,2.0,1.0,-32.4,-32.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6678,2022-05-02 04:00:00,Deepfreezer,1,exceed,-32,-30.6,1.9,1.1,-30.6,-30.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6679,2022-05-02 04:15:00,Deepfreezer,1,exceed,-32,-30.3,1.5,0.9,-30.4,-30.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6680,2022-05-02 05:15:00,Deepfreezer,0,recovery,-32,-33.1,3.0,2.0,-33.1,-33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6681,2022-05-02 05:15:00,Deepfreezer,0,recovery,-32,-33.0,3.0,2.0,-33.1,-33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6682,2022-05-02 07:45:00,Deepfreezer,1,exceed,-32,-31.8,2.3,0.8,-31.8,-31.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6683,2022-05-02 08:00:00,Deepfreezer,1,exceed,-32,-31.4,2.6,1.6,-31.9,-31.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6684,2022-05-02 08:00:00,Freezer,0,recovery,-24,-23.9,2.6,1.6,-31.9,-31.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6685,2022-05-02 08:00:00,Freezer,0,recovery,-24,-23.9,2.6,1.6,-31.9,-31.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6686,2022-05-02 08:15:00,Deepfreezer,0,recovery,-32,-32.0,3.1,2.0,-32.0,-31.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6687,2022-05-02 09:00:00,Freezer,1,deficit,-24,-24.2,3.1,2.3,-31.8,-31.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6688,2022-05-02 09:30:00,Deepfreezer,0,recovery,-32,-32.1,2.0,1.0,-32.4,-32.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6689,2022-05-02 09:30:00,Freezer,1,deficit,-24,-24.7,2.0,1.0,-32.4,-32.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6690,2022-05-02 11:45:00,Deepfreezer,1,deficit,-34,-34.2,2.6,1.8,-34.2,-33.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6691,2022-05-02 12:15:00,Deepfreezer,0,recovery,-34,-33.7,3.4,2.4,-33.7,-33.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6692,2022-05-02 15:00:00,Deepfreezer,1,exceed,-32,-30.4,3.0,2.5,-30.4,-30.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6693,2022-05-02 15:00:00,Deepfreezer,1,exceed,-32,-30.1,3.0,2.5,-30.4,-30.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6694,2022-05-02 16:15:00,Deepfreezer,0,recovery,-32,-32.0,1.8,1.2,-32.0,-31.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6695,2022-05-02 16:30:00,Deepfreezer,0,recovery,-32,-32.0,2.0,1.5,-32.5,-32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6696,2022-05-02 19:15:00,Freezer,0,recovery,-24,-23.8,2.3,2.0,-32.7,-32.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6697,2022-05-02 19:15:00,Freezer,0,recovery,-24,-23.9,2.3,2.0,-32.7,-32.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6698,2022-05-02 20:00:00,Freezer,0,recovery,-24,-23.9,1.6,0.9,-29.7,-29.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6699,2022-05-02 20:15:00,Deepfreezer,1,exceed,-32,-29.5,2.1,1.6,-29.5,-29.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
# For this case due that we don't have weather data up to may 22 2022 we will need to drop last 450 rows.

# Number of rows to drop
n = 450
 
# Dropping last n rows using drop
df_weather_alarms = df_weather_alarms.drop(df_weather_alarms.tail(n).index,
        inplace = False)
 
# Printing dataframe
df_weather_alarms.shape

(6673, 44)

In [91]:
# We will drop columns we don't need

df_weather_alarms = df_weather_alarms.drop(['temp_min', 'temp_max', 'dt_iso','timezone', 'city_name', 'lat', 'lon', 'visibility', 'dew_point', 'feels_like', 'pressure', 'sea_level', 'grnd_level', 'wind_speed', 'wind_deg', 'wind_gust', 'rain_1h', 'rain_3h', 'snow_3h', 'clouds_all', 'weather_id', 'weather_main', 'weather_description', 'weather_icon', 'snow_1h'], inplace=False, axis=1)

print(df_weather_alarms.shape)

df_weather_alarms.head()

(6673, 19)

,date,location,status,alarm_type,limit,value,platform_1,platform_2,deepfreezer_1,deepfreezer_2,freezer_1,freezer_2,freezer_3,freezer_4,cooling_1,cooling_2,sensor_alarm,temp,humidity
0,2021-06-24 16:45:00,Freezer,0,recovery,-19,-19.3,3.7,1.4,-20.0,-22.9,-19.3,-19.1,-18.1,-20.8,3.9,3.9,freezer_1,NaN,NaN
1,2021-06-24 16:45:00,Freezer,0,recovery,-19,-19.1,3.7,1.4,-20.0,-22.9,-19.3,-19.1,-18.1,-20.8,3.9,3.9,freezer_2,NaN,NaN
2,2021-06-24 17:00:00,Freezer,0,recovery,-19,-20.0,2.3,0.1,-23.0,-24.0,-20.2,-19.9,-20.0,-21.6,3.4,3.5,freezer_3,19.68,62.0
3,2021-06-24 17:30:00,Deepfreezer,0,recovery,-25,-25.9,2.4,0.6,-25.9,-25.0,-20.9,-20.8,-21.2,-22.1,3.1,3.2,deepfreezer_1,NaN,NaN
4,2021-06-24 17:30:00,Deepfreezer,0,recovery,-25,-25.0,2.4,0.6,-25.9,-25.0,-20.9,-20.8,-21.2,-22.1,3.1,3.2,deepfreezer_2,NaN,NaN

In [92]:
# Fill values weather values using fillna()

df_weather_alarms = df_weather_alarms.fillna(method='ffill')

df_weather_alarms = df_weather_alarms.dropna()

print(df_weather_alarms.shape)
df_weather_alarms.head(20)

(6671, 19)

,date,location,status,alarm_type,limit,value,platform_1,platform_2,deepfreezer_1,deepfreezer_2,freezer_1,freezer_2,freezer_3,freezer_4,cooling_1,cooling_2,sensor_alarm,temp,humidity
2,2021-06-24 17:00:00,Freezer,0,recovery,-19,-20.0,2.3,0.1,-23.0,-24.0,-20.2,-19.9,-20.0,-21.6,3.4,3.5,freezer_3,19.68,62.0
3,2021-06-24 17:30:00,Deepfreezer,0,recovery,-25,-25.9,2.4,0.6,-25.9,-25.0,-20.9,-20.8,-21.2,-22.1,3.1,3.2,deepfreezer_1,19.68,62.0
4,2021-06-24 17:30:00,Deepfreezer,0,recovery,-25,-25.0,2.4,0.6,-25.9,-25.0,-20.9,-20.8,-21.2,-22.1,3.1,3.2,deepfreezer_2,19.68,62.0
5,2021-06-24 17:45:00,Platform,1,deficit,1,0.6,2.4,0.6,-26.4,-25.4,-21.0,-21.0,-21.5,-22.2,3.1,3.2,platform_2,19.68,62.0
6,2021-06-24 19:15:00,Platform,1,deficit,1,0.8,0.8,-0.9,-27.2,-26.2,-21.1,-21.0,-22.2,-22.4,3.0,3.1,platform_1,19.68,62.0
7,2021-06-24 19:30:00,Platform,0,recovery,1,1.1,1.1,-0.5,-27.6,-26.3,-21.1,-20.9,-22.3,-22.4,3.0,3.1,platform_1,19.68,62.0
8,2021-06-24 21:00:00,Platform,1,deficit,1,0.7,0.7,-1.1,-27.7,-26.9,-20.8,-20.7,-21.6,-22.3,3.4,3.2,platform_1,22.02,55.0
9,2021-06-24 21:15:00,Platform,0,recovery,1,1.1,1.1,-0.6,-27.7,-27.0,-20.8,-20.8,-21.7,-22.3,3.5,3.3,platform_1,22.02,55.0
10,2021-06-24 22:00:00,Platform,0,recovery,1,1.2,1.2,-0.3,-27.7,-27.2,-20.9,-21.3,-22.8,-22.2,3.8,3.4,platform_1,19.58,59.0
11,2021-06-24 22:15:00,Platform,0,recovery,1,1.3,2.3,1.3,-27.4,-27.3,-21.0,-21.5,-23.0,-22.2,4.0,3.5,platform_2,19.58,59.0
12,2021-06-24 22:30:00,Freezer,1,deficit,-23,-23.1,2.1,1.2,-27.0,-27.2,-21.0,-21.7,-23.1,-22.2,4.1,3.5,freezer_3,19.58,59.0
13,2021-06-24 22:45:00,Platform,1,deficit,1,-0.4,1.7,-0.4,-26.6,-27.2,-21.0,-21.6,-22.9,-22.2,4.2,3.6,platform_2,19.58,59.0
14,2021-06-24 22:45:00,Freezer,0,recovery,-23,-22.9,1.7,-0.4,-26.6,-27.2,-21.0,-21.6,-22.9,-22.2,4.2,3.6,freezer_3,19.58,59.0
15,2021-06-24 23:00:00,Freezer,1,deficit,-23,-23.2,1.5,-0.3,-26.4,-27.0,-21.1,-21.6,-23.2,-22.2,4.3,3.7,freezer_3,16.73,62.0
16,2021-06-24 23:30:00,Freezer,0,recovery,-23,-22.7,1.6,-0.6,-25.9,-26.8,-21.1,-21.3,-22.7,-22.2,4.5,3.9,freezer_3,16.73,62.0
17,2021-06-25 01:15:00,Platform,1,deficit,1,0.3,0.3,-1.5,-25.0,-26.1,-20.9,-21.1,-21.9,-22.2,3.4,4.0,platform_1,16.73,62.0
18,2021-06-25 01:45:00,Platform,0,recovery,1,1.2,1.2,-0.3,-24.4,-26.0,-21.0,-21.2,-21.9,-22.2,3.2,3.8,platform_1,16.73,62.0
19,2021-06-25 01:45:00,Deepfreezer,1,exceed,-25,-24.4,1.2,-0.3,-24.4,-26.0,-21.0,-21.2,-21.9,-22.2,3.2,3.8,deepfreezer_1,16.73,62.0
20,2021-06-25 02:00:00,Deepfreezer,0,recovery,-25,-25.3,1.2,-0.4,-25.3,-25.8,-20.9,-21.3,-22.1,-22.2,2.9,3.7,deepfreezer_1,17.78,81.0
21,2021-06-25 04:15:00,Platform,1,deficit,1,0.5,0.5,-1.2,-26.3,-26.3,-21.0,-21.1,-22.2,-22.1,3.1,3.4,platform_1,17.78,81.0

In [93]:
# Check if there are still NaNs
df_weather_alarms.isnull().sum()

date             0
location         0
status           0
alarm_type       0
limit            0
value            0
platform_1       0
platform_2       0
deepfreezer_1    0
deepfreezer_2    0
freezer_1        0
freezer_2        0
freezer_3        0
freezer_4        0
cooling_1        0
cooling_2        0
sensor_alarm     0
temp             0
humidity         0
dtype: int64

In [94]:
# Import df as csv
df_weather_alarms.to_csv('Resources/saveris_alarms_weather.csv')

In [95]:
df_weather_alarms.dtypes

date             datetime64[ns]
location                 object
status                    int64
alarm_type               object
limit                     int64
value                   float64
platform_1              float64
platform_2              float64
deepfreezer_1           float64
deepfreezer_2           float64
freezer_1               float64
freezer_2               float64
freezer_3               float64
freezer_4               float64
cooling_1               float64
cooling_2               float64
sensor_alarm             object
temp                    float64
humidity                float64
dtype: object